build-job:
  artifacts:
    paths:
      - build
  image: "node:16.15.1"
  only:
    - master
  script:
    - "echo \"Compiling the code...\""
    - yarn
    - "yarn build"
    - "echo \"Compile complete.\""
  stage: build
deploy-dev-job:
  image:
    entrypoint:
      - ""
    name: amazon/aws-cli
  only:
    - develop
  script:
    - "aws --version"
    - "aws s3 rm s3://$S3_BUCKET_DEV --recursive"
    - "aws s3 cp build s3://$S3_BUCKET_DEV --recursive"
  stage: deploy
deploy-prod-job:
  image:
    entrypoint:
      - ""
    name: amazon/aws-cli
  only:
    - master
  script:
    - "aws --version"
    - "aws s3 rm s3://$S3_BUCKET_PROD --recursive"
    - "aws s3 cp build s3://$S3_BUCKET_PROD --recursive"
  stage: deploy-prod
stages:
  - build
  - deploy-dev
  - deploy-prod
