build-job:
  artifacts:
    paths:
      - build
  image: "node:16.15.1"
  only:
    - dev
  script:
    - "echo \"Compiling the code...\""
    - yarn
    - "yarn build"
    - "echo \"Compile complete.\""
  stage: build

deploy-dev-job:
  image:
    entrypoint:
      - ""
    name: amazon/aws-cli
  only:
    - dev
  script:
    - "aws --version"
    - "aws s3 rm s3://$S3_BUCKET_DEV --recursive"
    - "aws s3 cp build s3://S3_BUCKET_DEV --recursive"
    - "aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID_DEV --paths '/*'"
  stage: deploy-dev
stages:
  - build
  - deploy-dev
